name: TESTS

on:
  pull_request_target:
    branches:
      - dev
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install yarn
        run: npm install yarn -g

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Cypress Integration Tests
        run: yarn e2e

      - name: Cypress Unit Tests
        run: yarn cy:run-ct

      - name: Coverage
        run: yarn coverage
